name       : qpdf
version    : 11.1.1
release    : 20
source     :
    - https://github.com/qpdf/qpdf/releases/download/v11.1.1/qpdf-11.1.1.tar.gz : 25e8ec60e290cd134405a51920015b6d351d4e0b93b7b736d257f10725f74b5a
homepage   : https://github.com/qpdf/qpdf
license    : Apache-2.0
component  : desktop.core
summary    : PDF manipulation library
description: |
    QPDF is a C++ library and set of programs that inspect and manipulate the structure of PDF files. It can encrypt and linearize files, expose the internals of a PDF file, and do many other operations useful to end users and PDF developers.
builddeps  :
    - pkgconfig(libturbojpeg)
setup      : |
    %cmake_ninja \
        -DBUILD_DOC=OFF \
        -DINSTALL_EXAMPLES=OFF \
        -DBUILD_STATIC_LIBS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # install bash and zsh completions
    install -Dm00644 completions/bash/qpdf $installdir/usr/share/bash-completion/completions/qpdf
    install -Dm00644 completions/zsh/_qpdf $installdir/usr/share/zsh/site-functions/_qpdf

    rm -r $installdir/usr/share/doc
check      : |
    %ninja_check
