name       : qpdf
version    : 11.2.0
release    : 21
source     :
    - https://github.com/qpdf/qpdf/releases/download/v11.2.0/qpdf-11.2.0.tar.gz : fbd2d75050933487929dbbe1b5c50a238487194bc7263c277d6e49abb90ab7f2
homepage   : https://github.com/qpdf/qpdf
license    : Apache-2.0
component  : desktop.core
summary    : PDF manipulation library
description: |
    QPDF is a C++ library and set of programs that inspect and manipulate the structure of PDF files. It can encrypt and linearize files, expose the internals of a PDF file, and do many other operations useful to end users and PDF developers.
builddeps  :
    - pkgconfig(libturbojpeg)
setup      : |
    %cmake_ninja \
        -DBUILD_DOC=OFF \
        -DINSTALL_EXAMPLES=OFF \
        -DBUILD_STATIC_LIBS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # install bash and zsh completions
    install -Dm00644 completions/bash/qpdf $installdir/usr/share/bash-completion/completions/qpdf
    install -Dm00644 completions/zsh/_qpdf $installdir/usr/share/zsh/site-functions/_qpdf

    rm -r $installdir/usr/share/doc
check      : |
    %ninja_check
