name       : qpdf
version    : 8.4.1
release    : 10
source     :
    - https://github.com/qpdf/qpdf/releases/download/release-qpdf-8.4.1/qpdf-8.4.1.tar.gz : 07fd02b8b32f760ea86c1999f5a67086126437ea854b4064f02c55dbd0f04ebb
license    : Apache-2.0
component  : desktop.core
summary    : PDF manipulation library
description: |
    QPDF is a C++ library and set of programs that inspect and manipulate the structure of PDF files. It can encrypt and linearize files, expose the internals of a PDF file, and do many other operations useful to end users and PDF developers.
builddeps  :
    - pkgconfig(libturbojpeg)
setup      : |
    %configure --disable-static --enable-show-failed-test-output
build      : |
    %make
install    : |
    %make_install

    install -Dm00644 completions/bash/qpdf $installdir/usr/share/bash-completion/completions/qpdf
    install -Dm00644 completions/zsh/_qpdf $installdir/usr/share/zsh/site-functions/_qpdf
check      : |
    %make check
