name       : qpdf
version    : 6.0.0
release    : 1
source     :
    - http://downloads.sourceforge.net/qpdf/qpdf-6.0.0.tar.gz : a9fdc7e94d38fcd3831f37b6e0fe36492bf79aa6d54f8f66062cf7f9c4155233
license    : Artistic-2.0
summary    : PDF manipulation library
description: |
    PDF manipulation library
builddeps  :
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
