name       : qpdf
version    : 10.3.2
release    : 14
source     :
    - https://github.com/qpdf/qpdf/releases/download/release-qpdf-10.3.2/qpdf-10.3.2.tar.gz : 062808c40ef8741ec8160ae00168638a712cfa1d4bf673e8e595ab5eba1da947
homepage   : https://github.com/qpdf/qpdf
license    : Apache-2.0
component  : desktop.core
summary    : PDF manipulation library
description: |
    QPDF is a C++ library and set of programs that inspect and manipulate the structure of PDF files. It can encrypt and linearize files, expose the internals of a PDF file, and do many other operations useful to end users and PDF developers.
builddeps  :
    - pkgconfig(libturbojpeg)
setup      : |
    %configure --disable-static --enable-show-failed-test-output
build      : |
    %make
install    : |
    %make_install

    install -Dm00644 completions/bash/qpdf $installdir/usr/share/bash-completion/completions/qpdf
    install -Dm00644 completions/zsh/_qpdf $installdir/usr/share/zsh/site-functions/_qpdf
check      : |
    %make check
