name       : qpdf
version    : 8.2.1
release    : 7
source     :
    - https://github.com/qpdf/qpdf/releases/download/release-qpdf-8.2.1/qpdf-8.2.1.tar.gz : f445d3ebda833fe675b7551378f41fa1971cc6f7a7921bbbb94d3a71a404abc9
license    : Apache-2.0
component  : desktop.core
summary    : PDF manipulation library
description: |
    QPDF is a C++ library and set of programs that inspect and manipulate the structure of PDF files. It can encrypt and linearize files, expose the internals of a PDF file, and do many other operations useful to end users and PDF developers.
builddeps  :
    - pkgconfig(libturbojpeg)
setup      : |
    %configure --disable-static --enable-show-failed-test-output
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
