name       : qpdf
version    : 8.3.0
release    : 8
source     :
    - https://github.com/qpdf/qpdf/releases/download/release-qpdf-8.3.0/qpdf-8.3.0.tar.gz : 46c2a10690b86ba680db1c828e9ce44bb8e2993f69aa96d5a52fd1d98dc391f7
license    : Apache-2.0
component  : desktop.core
summary    : PDF manipulation library
description: |
    QPDF is a C++ library and set of programs that inspect and manipulate the structure of PDF files. It can encrypt and linearize files, expose the internals of a PDF file, and do many other operations useful to end users and PDF developers.
builddeps  :
    - pkgconfig(libturbojpeg)
setup      : |
    %configure --disable-static --enable-show-failed-test-output
build      : |
    %make
install    : |
    %make_install

    install -Dm00644 completions/bash/qpdf $installdir/usr/share/bash-completion/completions/qpdf
    install -Dm00644 completions/zsh/_qpdf $installdir/usr/share/zsh/site-functions/_qpdf
check      : |
    %make check
