name       : qpdf
version    : 7.1.0
release    : 3
source     :
    - https://kent.dl.sourceforge.net/project/qpdf/qpdf/7.1.0/qpdf-7.1.0.tar.gz : 27054bfb83a4f4f70053c6d4c2de5e18ddf60c9a8edbce219ac1bdcf03f16a2e
license    : Apache-2.0
component  : desktop.core
summary    : PDF manipulation library
description: |
    QPDF is a C++ library and set of programs that inspect and manipulate the structure of PDF files. It can encrypt and linearize files, expose the internals of a PDF file, and do many other operations useful to end users and PDF developers.
builddeps  :
    - pkgconfig(libturbojpeg)
setup      : |
    %configure --disable-static --enable-show-failed-test-output
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
