name       : qpdf
version    : 7.0.0
release    : 2
source     :
    - https://kent.dl.sourceforge.net/project/qpdf/qpdf/7.0.0/qpdf-7.0.0.tar.gz : fed08de14caad0fe5efd148d9eca886d812588b2cbb35d13e61993ee8eb8c65f
license    : Apache-2.0
component  : desktop.core
summary    : PDF manipulation library
description: |
    QPDF is a C++ library and set of programs that inspect and manipulate the structure of PDF files. It can encrypt and linearize files, expose the internals of a PDF file, and do many other operations useful to end users and PDF developers.
builddeps  :
    - pkgconfig(libturbojpeg)
setup      : |
    %configure --disable-static --enable-show-failed-test-output
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
